theme = "github.com/jpanther/lynx"
title = "Hyper"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Hyper"
  headline = ""
  image = "author.jpg"
  links = [
    { camera = { href = "https://photo.felle.me", text = "Photography", icon = "camera" } },
    { telegram = "https://t.me/jordanfelle" },
    { furtrack = { href = "https://www.furtrack.com/user/Hyper", text = "Furtrack", icon = "furtrack" } },
    { bluesky = "https://bsky.app/profile/hypercat.me" },
    { kofi = { href = "https://ko-fi.com/jordanfelle  ", text = "Kofi", icon = "kofi" } },
    { twitter = "https://twitter.com/jordanfelle" },
    { instagram = "https://www.instagram.com/hyper123" },
    { facebook = "https://www.facebook.com/hyper123" },
    { lastfm = "https://www.last.fm/user/hyper123123" },
    { steam = "https://steamcommunity.com/id/hyper123" },
    { github = "https://github.com/jordanfelle" },
    { discord = "https://discord.com/users/307919782961872897" },
    { trakt = { href = "https://trakt.tv/users/hyper123", text = "Trakt", icon = "trakt" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
